### PR TITLE
JENKINS-26881 : fixed by removing unnecessary typecast to GStringImpl.

### PR DESCRIPTION
**Pull request by danielburgmann**

### CODE REVIEW

**Comment by daniel-beck** [comment]
@bkmeneguello [The author of this PR asks for commit access to the repository to be able to merge it](https://groups.google.com/d/msg/jenkinsci-dev/d4khKWRfkKs/FCWHRBdfAQAJ). Any opinions on this?

**Comment by bkmeneguello** [comment]
Sure, give him access. I'm without time to update this project.

**Comment by danielburgmann** [comment]
@daniel-beck Is there any additional action needed from my side?

**Comment by lkwg82** [comment]
Is the bug https://issues.jenkins-ci.org/browse/JENKINS-26881 still open, or resolved? Plz close it in case it is resolved!

**Pull request merged**
